/**
 * Best-effort MVP DOM scraper for Google Hotels
 * This structure changes often, so we use heuristics.
 */

// Keep track of cards we've already processed
const processedCards = new WeakSet();
const pendingVerifications = new Map();

function extractData(card) {
  // Title heuristic: look for h2, h3, or a div with role="heading"
  const titleEl = card.querySelector('h2, h3, [role="heading"]');
  const title = titleEl ? titleEl.innerText.trim() : '';
  
  // For demo purposes: Blur the real hotel name to avoid defamation/legal issues when showing fake scores
  if (titleEl) {
    titleEl.style.filter = 'blur(5px)';
    titleEl.style.userSelect = 'none';
    titleEl.style.opacity = '0.7';
  }

  // Price heuristic: look for currency signs ($ or ₹, £, €)
  const priceRegex = /[\$₹£€](\d+(?:,\d+)?)/;
  const textContent = card.innerText || '';
  const priceMatch = textContent.match(priceRegex);
  let price = 0;
  if (priceMatch) {
    price = parseInt(priceMatch[1].replace(',', ''), 10);
  }

  // Image heuristic: get the first large image
  const imgEl = card.querySelector('img');
  let imageUrls = [];
  if (imgEl && imgEl.src) {
    imageUrls = [imgEl.src];
  }

  const extracted = {
    title,
    price,
    imageUrls,
    domain: '', 
    location: '', 
    description: '',
    reviews: '' 
  };
  console.log("[StayVerify] Extracted data:", extracted);
  return extracted;
}

function injectBadge(card, result) {
  if (!result || !result.decision) return;
  
  // Make sure the card can hold absolute positioned elements
  if (getComputedStyle(card).position === 'static') {
    card.style.position = 'relative';
  }

  const score = result.decision.scam_risk?.score || 0;
  let riskClass = 'stayverify-low';
  if (score >= 0.3) riskClass = 'stayverify-med';
  if (score >= 0.7) riskClass = 'stayverify-high';

  const badge = document.createElement('div');
  badge.className = `stayverify-badge ${riskClass}`;
  badge.title = result.decision.explanation || "Risk analysis generated by StayVerify";
  
  // Use inline styles to guarantee visibility even if content.css fails to load due to SPA routing
  badge.style.cssText = `
    position: absolute;
    bottom: 16px;
    left: 16px;
    top: auto;
    z-index: 2147483647;
    background: rgba(15, 23, 42, 0.85);
    backdrop-filter: blur(16px);
    -webkit-backdrop-filter: blur(16px);
    border: 1px solid rgba(255, 255, 255, 0.15);
    border-top: 1px solid rgba(255, 255, 255, 0.3);
    border-radius: 12px;
    padding: 10px 12px;
    display: flex;
    flex-direction: column;
    align-items: center;
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.4), inset 0 0 0 1px ${score >= 0.7 ? 'rgba(239, 68, 68, 0.3)' : score >= 0.3 ? 'rgba(234, 179, 8, 0.3)' : 'rgba(34, 197, 94, 0.3)'};
    font-family: 'Inter', system-ui, -apple-system, sans-serif;
    color: white;
    min-width: 90px;
    pointer-events: none;
  `;
  
  const labelDiv = document.createElement('div');
  labelDiv.innerText = "SCAM RISK";
  labelDiv.style.cssText = `
    font-size: 0.6rem;
    text-transform: uppercase;
    font-weight: 800;
    opacity: 0.7;
    margin-bottom: 2px;
    letter-spacing: 0.5px;
  `;
  badge.appendChild(labelDiv);

  const scoreDiv = document.createElement('div');
  const scoreColor = score >= 0.7 ? '#ef4444' : score >= 0.3 ? '#facc15' : '#4ade80';
  scoreDiv.style.cssText = `
    font-size: 1.6rem;
    font-weight: 900;
    line-height: 1;
    margin-bottom: 6px;
    color: ${scoreColor};
    text-shadow: 0 2px 10px ${scoreColor}66;
    letter-spacing: -0.5px;
  `;
  scoreDiv.innerText = `${Math.round(score * 100)}%`;
  
  badge.appendChild(scoreDiv);

  const flagStyle = 'font-size: 0.65rem; text-transform: uppercase; margin-top: 4px; font-weight: 700; text-align: center; background: rgba(255, 255, 255, 0.1); padding: 3px 6px; border-radius: 4px; width: 100%; box-sizing: border-box; letter-spacing: 0.5px; border: 1px solid rgba(255, 255, 255, 0.05);';

  if (result.decision.primary_red_flag?.choice && result.decision.primary_red_flag.choice !== 'none_significant') {
    const flagDiv = document.createElement('div');
    flagDiv.style.cssText = flagStyle;
    if (result.decision.primary_red_flag.choice === 'insufficient_data') {
      flagDiv.innerText = "Missing Data";
      flagDiv.style.background = 'rgba(234, 179, 8, 0.3)'; // yellow
    } else {
      flagDiv.innerText = result.decision.primary_red_flag.choice.replace(/_/g, ' ');
    }
    badge.appendChild(flagDiv);
  } else if (result.decision.needs_human_review) {
    const flagDiv = document.createElement('div');
    flagDiv.style.cssText = flagStyle;
    flagDiv.innerText = "Review";
    badge.appendChild(flagDiv);
  }

  if (result.decision.photo_authenticity) {
    const photoDiv = document.createElement('div');
    photoDiv.style.cssText = flagStyle;
    photoDiv.innerText = result.decision.photo_authenticity.choice === 'ai_made' ? 'AI Photo' : 
                         result.decision.photo_authenticity.choice === 'stolen' ? 'Stolen Photo' : 'Real Photo';
    if (result.decision.photo_authenticity.choice === 'real') {
      photoDiv.style.background = 'rgba(16, 185, 129, 0.2)'; // Green for real
      photoDiv.style.color = '#a7f3d0';
      photoDiv.style.borderColor = 'rgba(16, 185, 129, 0.4)';
    } else {
      photoDiv.style.background = 'rgba(239, 68, 68, 0.2)'; // Red for AI/stolen
      photoDiv.style.color = '#fecaca';
      photoDiv.style.borderColor = 'rgba(239, 68, 68, 0.4)';
    }
    badge.appendChild(photoDiv);
  }

  if (result.decision.listing_legitimacy && result.decision.listing_legitimacy.choice !== 'real') {
    const legitDiv = document.createElement('div');
    legitDiv.style.cssText = flagStyle;
    legitDiv.innerText = result.decision.listing_legitimacy.choice === 'fake' ? 'Fake Hotel' : 'Duplicate Hotel';
    legitDiv.style.background = 'rgba(239, 68, 68, 0.2)';
    legitDiv.style.color = '#fecaca';
    legitDiv.style.borderColor = 'rgba(239, 68, 68, 0.4)';
    badge.appendChild(legitDiv);
  }

  card.appendChild(badge);
}

async function verifyCard(card) {
  if (processedCards.has(card)) return;
  processedCards.add(card);

  const data = extractData(card);
  
  // Only verify if we found a title and price
  if (!data.title || !data.price) return;

  chrome.runtime.sendMessage({ action: 'VERIFY_LISTING', data }, (response) => {
    console.log("[StayVerify] Received response from background:", response);
    if (chrome.runtime.lastError) {
      console.error("[StayVerify] Runtime Error:", chrome.runtime.lastError);
      return;
    }
    if (response && response.success) {
      console.log("[StayVerify] Injecting badge with data:", response.data);
      injectBadge(card, response.data);
    } else {
      console.error("[StayVerify] Verification failed:", response?.error);
    }
  });
}

// Intersection Observer for visibility debounce
const observer = new IntersectionObserver((entries) => {
  entries.forEach((entry) => {
    const card = entry.target;
    
    if (entry.isIntersecting) {
      // Start a 300ms timer to verify if it stays in view
      if (!pendingVerifications.has(card)) {
        const timerId = setTimeout(() => {
          verifyCard(card);
          pendingVerifications.delete(card);
          observer.unobserve(card); // Stop observing once verified
        }, 300);
        pendingVerifications.set(card, timerId);
      }
    } else {
      // Clear the timer if it goes out of view before 300ms
      if (pendingVerifications.has(card)) {
        clearTimeout(pendingVerifications.get(card));
        pendingVerifications.delete(card);
      }
    }
  });
}, {
  threshold: 0.5 // Require 50% visibility
});

function findAndObserveCards(root = document) {
  // Let's look for anything that might be a card
  const possibleCards = Array.from(root.querySelectorAll('a, div[role="listitem"], c-wiz'));
  
  let foundCount = 0;
  possibleCards.forEach(container => {
    // A card should have an image and a price, and shouldn't be the whole page
    if (container.querySelector('img') && /[\\$₹£€]/.test(container.innerText)) {
      
      // Ensure we don't observe a parent that contains multiple valid cards (list container)
      const nestedImages = container.querySelectorAll('img');
      if (nestedImages.length > 8) return;

      if (!processedCards.has(container)) {
        foundCount++;
        // Add a subtle border so we can visually see what was selected during debugging
        container.style.outline = "2px dashed blue";
        observer.observe(container);
      }
    }
  });
  if (foundCount > 0) {
    console.log(`[StayVerify] Found and observing ${foundCount} new cards.`);
  }
}

// Mutation Observer for dynamic loads
const mutationObserver = new MutationObserver((mutations) => {
  let hasNewNodes = false;
  for (const mutation of mutations) {
    if (mutation.addedNodes.length > 0) {
      hasNewNodes = true;
      break;
    }
  }
  
  if (hasNewNodes) {
    findAndObserveCards();
  }
});

// Start observing the body for DOM changes
mutationObserver.observe(document.body, { childList: true, subtree: true });

// Initial scan
findAndObserveCards();
